package com.sarief.minesweeper.entity;

import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * Information on minecell
 */
@Getter
@Setter
@Builder
public class MineCell {

    private MineCellCoordinates coordinates;
    private boolean open;
    private boolean marked; // marked with "flag"
    @Getter(AccessLevel.NONE)
    private boolean containsMine;
    private MineCellAdjacentInfo mineCellAdjacentInfo; // adjacent mine cells pointers

    // just sugar instead of lombok autogenerated name, because isContainsMine doesn't sound correct
    // and lombok won't do it either... https://github.com/projectlombok/lombok/issues/836
    public boolean containsMine(){
        return containsMine;
    }

}
